services:
  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - postgres_volume:/var/lib/postgres/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-"default_password}
    ports:
      - 5432:5432
    networks:
      - next_app_network

volumes:
  postgres_volume:

networks:
  next_app_network:
    external: true