services:
  next_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    tty: true
    user: node
    extra_hosts:
    - host.docker.internal:host-gateway
    networks:
      - next_app_network

networks:
  next_app_network:
    external: true
